name: Keep Alive

on:
  schedule:
    - cron: '0 */6 * * *'  # runs every 10 hours
  workflow_dispatch:          # allows manual trigger

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -L -A /dev/null -w "%{http_code}" https://climateaiapp-byvishistsharma.streamlit.app
